# Site
repository: CODEMCD/resume
# favicon: images/favicon.ico

# Personal info
name: 박성범
title: 백엔드 엔지니어 지망생
email: psbum1609@gmail.com
website: https://velog.io/@codemcd

# Social links
# twitter_username: CODEMCD
github_username: CODEMCD
# dribbble_username: jekyll
# facebook_username: devbeginner
# flickr_username: jekyll
# linkedin_username: CODEMCD
# pinterest_username: jekyll
# youtube_username: globalmtb

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  백엔드 개발자를 지망하는 학생으로서, 성장에 매우 관심이 많습니다.
  현제는 우아한테크코스를 수강중이고, 이전에는 POCU 아카데미에서 C++ 강좌를 수료하였습니다.
  OOP와 클린 코드를 통해 읽기 좋은 코드를 구현하려 노력하며, 
  테스트 코드를 작성하는 것을 당연하게 생각합니다. TDD에도 관심이 많습니다.
  배운 지식과 개발을 하며 생긴 이슈는 GITHUB와 블로그에 기록하고 있습니다.
  항상 과거의 나에게 고칠 점을 찾아 성장하기 위해 회고를 하고 있습니다.
  꾸준히 노력하여 좋은 개발자가 되기를 꿈꾸고 있습니다.
  

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  여러 주제로 발표와 기고를 해왔습니다.
   - [2019 우아한 스프링 배치](https://www.facebook.com/woowahanTech/photos/a.1925530564354206/2373861249521133/?type=3&theater) 
   - [인프런 - IntelliJ IDEA 가이드](https://www.inflearn.com/course/intellij-guide) 
   - [2018 KCD - IntelliJ IDEA만으로 개발하기](https://www.youtube.com/watch?v=wBXSUdT1jX0)
   - [2018 JetBrains Day - Upsource를 이용한 코드리뷰](https://www.youtube.com/watch?v=06bJt6CnRAU&feature=youtu.be)
   - [마소 394호 - AWS EC2와 TravisCI를 활용한 무중단 배포 서비스](http://it.chosun.com/site/data/html_dir/2018/10/29/2018102900482.html)
  
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
